import TopLeftImg from "@/components/TopLeftImg";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import Nav from "@/components/Nav";
import Header from "@/components/Header";
import Transition from "@/components/Transition";

const inter = Inter({ subsets: ["latin"] });
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-site text-white bg-cover bg-no-repeat ${sora.variable} min-h-screen flex flex-col font-sora relative min-w-full`}
      >
        <TopLeftImg />
        <Nav />
        <Header />
        <div className="flex flex-1">
          <Transition>{children}</Transition>
        </div>
      </body>
    </html>
  );
}
